<script setup lang="ts">
import { computed } from 'vue';

    const props = withDefaults(defineProps<{
        currentPage: number
        totalPages: number
        clasifitacionLvl:string
        disableLineFooter:boolean;
    }>(), {
        totalPages: 1,
        currentPage: 1,
        clasifitacionLvl:'UNCLASSIFIED',
        disableLineFooter: false
    })
    const ellipseColor = computed(() => {
            switch (props.clasifitacionLvl) {
                case 'CLASSIFIED':
                    return '#FF951A';
                case 'RESTRICTED':
                    return '#FF0B0B';
                case 'SECRET':
                    return '#951818';
                case 'UNCLASSIFIED':
                default:
                    return '#20B65F';
            }
    });
</script>

<template>
    <div class="report-line-footer" :style="{ display: disableLineFooter ? 'none' : '' }"></div>

    <div :style="{ backgroundColor: ellipseColor }" class="report-elipse"></div>

    <div class="report-pages">Page {{currentPage}}/{{ totalPages }}</div>

    <div class="report-unclassified-group">
        <div class="report-unclassified">{{clasifitacionLvl}}</div>
        <div class="report-unclassified-line"></div>
    </div>

    <div class="report-reproduced-group">
        <div class="report-reproduced-text">
            This document may not be reproduced, modified, adapted, published, translated, in any way, in whole or
            in part, or disclosed to a third party without the prior written consent of ASI - Agenzia Spaziale
            Italiana.
        </div>

        <div class="report-document-generated-text">
            Document generated by PLATiNO Shutter Control System
        </div>
    </div>
</template>

<style scoped>
.report-line-footer {
    width: 998px;
    height: 0px;
    left: 25px;
    top: 710px;
    position: absolute;
    border: 0.50px #B9B9B9 solid
}
.report-elipse {
    width: 13px;
    height: 13px;
    left: 25px;
    top: 723px;
    position: absolute;  
    border-radius: 9999px
}
.report-pages {
    width: 161px;
    height: 28px;
    left: 862px;
    top: 713px;
    position: absolute;
    text-align: right;
    color: black;
    font-size: 12px;
    font-family: Arial;
    font-weight: 400;
    word-wrap: break-word
}
.report-unclassified-group {
    width: 1070px;
    height: 28px;
    left: 25px;
    top: 700px;
    position: absolute
}
.report-unclassified {
    width: 161px;
    height: 15px;
    left: 16px;
    top: 14px;
    position: absolute;
    color: black;
    font-size: 12px;
    font-family: Arial;
    font-weight: 700;
    word-wrap: break-word
}

.report-reproduced-group {
    width: 746px;
    height: 28px;
    left: 25px;
    top: 633px;
    position: absolute
}
.report-reproduced-text {
    width: 630px;
    height: 15px;
    left: 0px;
    top: 100px;
    position: absolute;
    color: black;
    font-size: 8px;
    font-family: "Arial-Regular", Helvetica,Arial;
    font-weight: 400;
    word-wrap: break-word
}
.report-document-generated-text {
    width: 456px;
    height: 15px;
    left: 0px;
    top: 136px;
    position: absolute;
    color: black;
    font-size: 7px;
    font-family: "Arial-Italic", Helvetica,Arial;
    font-style: italic;
    font-weight: 400;
    word-wrap: break-word
}
</style>
