<script setup lang="ts">
import image_asi from './logo_asi.png'
import image_tas from './logo_tas.png'
</script>
<template>
    
      
    <div ref="pdfContent" id="pdfContent" class="hidden-content" >
    <img :src="image_asi" alt="Girl in a jacket" width="82" height="38.51" style="left: 25px; top: 25px; position: absolute"> 
    <img class="LogoThalesAleniaSpaceLeonardoV21" style="width: 91px; height: 44px; left: 128px; top: 21px; position: absolute" :src="image_tas" />
    <div class="Line415" style="width: 546px; height: 0px; left: 25px; top: 73px; position: absolute; border: 0.50px #B9B9B9 solid"></div>
    <div class="Line416" style="width: 27px; height: 0px; left: 120px; top: 29px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; border: 0.50px #B9B9B9 solid"></div>
    <div class="PlatinoShutterControl13May2023" style="width: 161px; height: 28px; left: 407px; top: 36px; position: absolute; text-align: right; color: black; font-size: 10px; font-family: Roboto; font-weight: 400; word-wrap: break-word">PLATiNO SHUTTER CONTROL<br/>13 May 2023 </div>
    <div class="Line417" style="width: 546px; height: 0px; left: 25px; top: 755px; position: absolute; border: 0.50px #B9B9B9 solid"></div>
    <div class="Page134" style="width: 161px; height: 28px; left: 410px; top: 767px; position: absolute; text-align: right; color: black; font-size: 10px; font-family: Roboto; font-weight: 400; word-wrap: break-word">Page 1/34</div>
    <div class="Group14697" style="width: 456px; height: 43px; left: 25px; top: 783px; position: absolute">
      <div class="DocumentGeneratedByPlatinoShutterControlSystem" style="width: 456px; height: 15px; left: 0px; top: 28px; position: absolute; color: black; font-size: 7px; font-family: Inter; font-style: italic; font-weight: 400; word-wrap: break-word">Document generated by PLATiNO Shutter Control System</div>
      <div class="ThisDocumentMayNotBeReproducedModifiedAdaptedPublishedTranslatedInAnyWayInWholeOrInPartOrDisclosedToAThirdPartyWithoutThePriorWrittenConsentOfAsiAgenziaSpazialeItaliana" style="width: 456px; height: 15px; left: 0px; top: 0px; position: absolute; color: black; font-size: 8px; font-family: Inter; font-weight: 400; word-wrap: break-word">This document may not be reproduced, modified, adapted, published, translated, in any way, in whole or in part, or disclosed to a third party without the prior written consent of ASI - Agenzia Spaziale Italiana.</div>
    </div>
    <div class="Group14696" style="width: 546px; height: 28px; left: 25px; top: 755px; position: absolute">
      <div class="Unclassified" style="width: 161px; height: 15px; left: 16px; top: 13px; position: absolute; color: black; font-size: 10px; font-family: Roboto; font-weight: 700; word-wrap: break-word">UNCLASSIFIED</div>
      <div class="Line417" style="width: 546px; height: 0px; left: 0px; top: 0px; position: absolute; border: 0.50px #B9B9B9 solid"></div>
    </div>
    <div class="Ellipse360" style="width: 13px; height: 13px; left: 25px; top: 767px; position: absolute; background: #20B65F; border-radius: 9999px"></div>
    <div class="Overview" style="width: 544px; height: 16px; left: 24px; top: 583px; position: absolute; color: black; font-size: 12px; font-family: Inter; font-weight: 400; word-wrap: break-word">Overview</div>
    <div class="Group14739" style="width: 127px; height: 101px; left: 25px; top: 610px; position: absolute">
      <div class="Rectangle5729" style="width: 127px; height: 101px; left: 0px; top: 0px; position: absolute; background: #EEEEEE; border: 0.50px rgba(0, 0, 0, 0) solid"></div>
      <div class="Users" style="width: 127px; height: 24px; left: 0px; top: 41px; position: absolute; text-align: center; color: black; font-size: 20px; font-family: Inter; font-weight: 700; word-wrap: break-word">17 users</div>
    </div>
    <div class="UsersReportCustomizableExportTitle" style="width: 544px; height: 54px; left: 25px; top: 96px; position: absolute"><span style="color: black; font-size: 12px; font-family: Inter; font-weight: 400; word-wrap: break-word">Users Report<br/></span><span style="color: black; font-size: 16px; font-family: Inter; font-weight: 700; word-wrap: break-word">[customizable export title] </span></div>
    <div class="Group14805" style="width: 545px; height: 364px; left: 25px; top: 186px; position: absolute">
      <div class="Rectangle5726" style="width: 545px; height: 364px; left: 0px; top: 0px; position: absolute; background: #EEEEEE"></div>
      <div class="PlatinoImgFormatoOrizzontale" style="width: 247px; height: 16px; left: 17px; top: 15px; position: absolute; color: #0947E7; font-size: 14px; font-family: Inter; font-weight: 400; word-wrap: break-word">PLATiNO IMG - formato orizzontale</div>
    </div>
  </div>
  </template>
  <style scoped>
  .hidden-content {
    display: block;
    position: absolute;
    z-index: -10 !important;
    width: 595.28px;
    color: black;
    background: white;
    overflow: hidden;
     height: 842px; 
  }
  </style>